skillMetadata:
   sections:
      - name: Kuki Account
        fields:
          - type: label
            label: You must have a Kuki account to access IPTV services. Provide your Kuki ID username (for example e-mail) and password.

          - name: user
            type: text
            label: Username
            value:
            placeholder: Kuki ID for example e-mail address, etc.

          - name: password
            type: password
            label: Password
            value:
       
      - name": Kuki Default Device
        fields:
          - type: label
            value:
            label: You can prefer Kuki device for playing TV and remotely control it using Mycroft.
                   
          - name: default_device
            type: text
            label: Your prefered Kuki device
            value":
            placeholder: Name of your prefered Kuki device
