skillMetadata:
   sections:
      - name: Kuki Account
        fields:
          - type: label
            label: You must have a Kuki account to access IPTV services. Provide your Kuki ID username (for example e-mail) and password.

          - name: user
            type: text
            label: Username
            value:
            placeholder: Kuki ID for example e-mail address, etc.

          - name: password
            type: password
            label: Password
            value:
